<?php

namespace PAPS\LivraisonBundle\Repository;

/**
 * papserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class papserRepository extends \Doctrine\ORM\EntityRepository
{
}
