paps_livraison_homepage:
    path:     /
    defaults: { _controller: PAPSLivraisonBundle:Default:index }

index:
    path:     /index
    defaults: { _controller: PAPSLivraisonBundle:Front:index }

inscoursier:
    path:     /inscoursier
    defaults: { _controller: PAPSLivraisonBundle:Front:inscoursier }

contact:
    path:     /contact
    defaults: { _controller: PAPSLivraisonBundle:Front:contact }

service:
    path:     /service
    defaults: { _controller: PAPSLivraisonBundle:Front:service }

about:
    path:     /about
    defaults: { _controller: PAPSLivraisonBundle:Front:about }

