<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdntnub\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdntnub/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYdntnub.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYdntnub\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYdntnub\appProdProjectContainer(array(
    'container.build_hash' => 'Ydntnub',
    'container.build_id' => '919bee4b',
    'container.build_time' => 1535744315,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdntnub');
