<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZsgw9df\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZsgw9df/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZsgw9df.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZsgw9df\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZsgw9df\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zsgw9df',
    'container.build_id' => 'acac4d59',
    'container.build_time' => 1534777822,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZsgw9df');
