<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGjr5lct\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGjr5lct/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGjr5lct.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGjr5lct\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGjr5lct\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gjr5lct',
    'container.build_id' => 'a307d518',
    'container.build_time' => 1535805540,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGjr5lct');
